#!/bin/bash
# ============================================================
# Setup Android Build Environment
# Installs: JDK, Gradle, Android SDK + NDK, generates wrapper
# ============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ANDROID_DIR="$PROJECT_ROOT/android"

echo "=== Android Build Environment Setup ==="
echo ""

# -------------------------------------------------------
# 1. Java JDK 17
# -------------------------------------------------------
if java -version 2>&1 | grep -q "version"; then
    echo "[JDK] Already installed"
    java -version 2>&1 | head -1
else
    echo "[JDK] Installing OpenJDK 17..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq openjdk-17-jdk-headless
    echo "[JDK] Installed"
fi
export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
echo "  JAVA_HOME=$JAVA_HOME"
echo ""

# -------------------------------------------------------
# 2. Android SDK Command-line Tools
# -------------------------------------------------------
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
mkdir -p "$ANDROID_HOME"

if [ -f "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
    echo "[SDK] Command-line tools already installed"
else
    echo "[SDK] Installing Android command-line tools..."
    SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    SDK_ZIP="/tmp/android-cmdline-tools.zip"
    wget -q --show-progress -O "$SDK_ZIP" "$SDK_TOOLS_URL"
    mkdir -p "$ANDROID_HOME/cmdline-tools"
    unzip -qo "$SDK_ZIP" -d "$ANDROID_HOME/cmdline-tools/"
    mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest" 2>/dev/null || true
    echo "[SDK] Command-line tools installed"
fi

export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
echo "  ANDROID_HOME=$ANDROID_HOME"
echo ""

# -------------------------------------------------------
# 3. Accept licenses + install SDK components
# -------------------------------------------------------
echo "[SDK] Installing SDK components..."
yes | sdkmanager --licenses >/dev/null 2>&1 || true
sdkmanager --install \
    "platform-tools" \
    "platforms;android-34" \
    "build-tools;34.0.0" \
    "ndk;25.2.9519653" \
    "cmake;3.22.1" \
    2>&1 | grep -E "(Installing|done)" || true

export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/25.2.9519653"
echo "  ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
echo ""

# -------------------------------------------------------
# 4. Generate local.properties
# -------------------------------------------------------
echo "[GRADLE] Writing local.properties..."
cat > "$ANDROID_DIR/local.properties" << EOF
sdk.dir=$ANDROID_HOME
ndk.dir=$ANDROID_NDK_HOME
EOF
echo "  Written: android/local.properties"
echo ""

# -------------------------------------------------------
# 5. Generate Gradle wrapper
# -------------------------------------------------------
GRADLE_VERSION="8.3"
WRAPPER_DIR="$ANDROID_DIR/gradle/wrapper"
mkdir -p "$WRAPPER_DIR"

# gradle-wrapper.properties
cat > "$WRAPPER_DIR/gradle-wrapper.properties" << EOF
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
echo "[GRADLE] Created gradle-wrapper.properties (Gradle $GRADLE_VERSION)"

# Download gradle-wrapper.jar if missing
WRAPPER_JAR="$WRAPPER_DIR/gradle-wrapper.jar"
if [ ! -f "$WRAPPER_JAR" ]; then
    echo "[GRADLE] Downloading gradle-wrapper.jar..."
    # Download from Gradle releases
    GRADLE_DIST_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
    GRADLE_TMP="/tmp/gradle-${GRADLE_VERSION}.zip"
    if [ ! -f "$GRADLE_TMP" ]; then
        wget -q --show-progress -O "$GRADLE_TMP" "$GRADLE_DIST_URL"
    fi
    # Extract just the wrapper jar
    unzip -qo "$GRADLE_TMP" "gradle-${GRADLE_VERSION}/lib/gradle-wrapper-*.jar" -d /tmp/ 2>/dev/null || true
    EXTRACTED_JAR=$(find /tmp/gradle-${GRADLE_VERSION}/lib/ -name "gradle-wrapper-*.jar" 2>/dev/null | head -1)
    if [ -f "$EXTRACTED_JAR" ]; then
        cp "$EXTRACTED_JAR" "$WRAPPER_JAR"
        echo "[GRADLE] gradle-wrapper.jar installed"
    else
        echo "[GRADLE] WARNING: Could not extract wrapper JAR"
        echo "[GRADLE] Alternative: install Gradle and run 'cd android && gradle wrapper'"
    fi
fi

# Create gradlew script
cat > "$ANDROID_DIR/gradlew" << 'GRADLEW_EOF'
#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#

# Determine the app home
APP_HOME=$(cd "$(dirname "$0")" && pwd -P) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () { echo "$*"; } >&2
die () { echo "$*"; exit 1; } >&2

# OS specific support
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MSYS* | MINGW* ) msys=true ;;
  NonStop* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command in PATH."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in
      max*)
        MAX_FD=$(ulimit -H -n) ||
            warn "Could not query maximum file descriptor limit"
      ;;
    esac
    case $MAX_FD in
      '' | soft) :;;
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
      ;;
    esac
fi

# Collect all arguments for the java command
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
GRADLEW_EOF

chmod +x "$ANDROID_DIR/gradlew"
echo "[GRADLE] Created gradlew"

# -------------------------------------------------------
# 6. Summary
# -------------------------------------------------------
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Environment variables (add to ~/.bashrc):"
echo "  export JAVA_HOME=$JAVA_HOME"
echo "  export ANDROID_HOME=$ANDROID_HOME"
echo "  export ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
echo "  export PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH"
echo ""
echo "Next steps:"
echo "  1. ./scripts/setup_android_deps.sh   # Download ORT + build SentencePiece"
echo "  2. ./scripts/prepare_models_android.sh  # Quantize + copy models"
echo "  3. cd android && ./gradlew assembleDebug  # Build APK"
echo "  4. adb install app/build/outputs/apk/debug/app-debug.apk"
